name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: ['3.7', '3.8', '3.9']
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Test with pytest
      run: |
        pipenv run bash ./scripts/test.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1