name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock
    - name: Test with pytest
      run: |
        bash ./scripts/test.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1